# Nord 配色方案
# background=#2e3440
# foreground=#d8dee9
# cursor=#81a1c1

# color0=#3b4252
# color8=#616e88
# color1=#bf616a
# color9=#bf616a
# color2=#a3be8c
# color10=#a3be8c
# color3=#ebcb8b
# color11=#ebcb8b
# color4=#81a1c1
# color12=#81a1c1
# color5=#b48ead
# color13=#b48ead
# color6=#8fbcbb
# color14=#8bc4c3
# color7=#e5e9f0
# color15=#eceff4

# Catppuccin Macchiato Termux背景配色（冷色基底带紫调）
background=#24273a
foreground=#cad3f5
cursor=#f5a97f

color0=#494d64
color8=#5b6078
color1=#c07a87
color9=#c07a87
color2=#8ab77e
color10=#8ab77e
color3=#c4b389
color11=#c4b389
color4=#7590cc
color12=#7590cc
color5=#c79fc0
color13=#c79fc0
color6=#75b0a7
color14=#75b0a7
color7=#9ba2bc
color15=#8a91a9